# Generated by Django 3.1.1 on 2020-10-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=32)),
                ('tag', models.CharField(default='', max_length=32)),
                ('work_area', models.CharField(default='', max_length=32)),
                ('operation_department', models.CharField(default='', max_length=32)),
                ('creater', models.CharField(default='', max_length=32)),
                ('modifier', models.CharField(default='', max_length=32)),
                ('intact', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentfaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_information', models.CharField(default='', max_length=200)),
                ('data_of_failure', models.DateField(default='')),
                ('repair_data', models.DateField(default='')),
                ('work_order_no', models.CharField(default='', max_length=32)),
                ('reporter', models.CharField(default='', max_length=32)),
                ('enforcer', models.CharField(default='', max_length=32)),
                ('implentention', models.CharField(default='', max_length=4000)),
                ('cid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.instrumnet')),
            ],
        ),
    ]
