# Generated by Django 3.1.1 on 2020-10-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20201008_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='iname',
            field=models.CharField(default=None, max_length=23),
        ),
    ]
