# Generated by Django 3.1.1 on 2020-10-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_instrument_iname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentfaults',
            name='data_of_failure',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='instrumentfaults',
            name='repair_data',
            field=models.DateField(),
        ),
    ]
