# Generated by Django 3.1.1 on 2020-10-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20201008_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='area',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='creater',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='iname',
            field=models.CharField(max_length=23),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='modifier',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='operation_department',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='tag',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='work_area',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='instrumentfaults',
            name='enforcer',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='instrumentfaults',
            name='fault_information',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='instrumentfaults',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instrumentfaults',
            name='implentention',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='instrumentfaults',
            name='reporter',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='instrumentfaults',
            name='work_order_no',
            field=models.CharField(max_length=32),
        ),
    ]
