# Generated by Django 3.1.1 on 2020-10-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20201008_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentfaults',
            old_name='data_of_failure',
            new_name='data',
        ),
    ]
