# Generated by Django 3.1.1 on 2020-10-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20201008_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='creater',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='instrument',
            name='hhh',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='instrument',
            name='iname',
            field=models.CharField(default=None, max_length=23),
        ),
        migrations.AddField(
            model_name='instrument',
            name='intact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='modifier',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='instrument',
            name='operation_department',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='instrument',
            name='tag',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='instrument',
            name='work_area',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='instrumentfaults',
            name='enforcer',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='instrumentfaults',
            name='implentention',
            field=models.CharField(default=None, max_length=4000),
        ),
        migrations.AddField(
            model_name='instrumentfaults',
            name='repairdata',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentfaults',
            name='work_order_no',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='area',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='instrumentfaults',
            name='fault_information',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='instrumentfaults',
            name='reporter',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
