# Generated by Django 3.1.1 on 2020-10-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20201012_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operationdepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oname', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Work_area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wname', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='hhh',
        ),
        migrations.AddField(
            model_name='instrumentfaults',
            name='photoafter',
            field=models.ImageField(default=None, upload_to='img'),
        ),
        migrations.AddField(
            model_name='instrumentfaults',
            name='photobefore',
            field=models.ImageField(default=None, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='operation_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.operationdepartment'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='work_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.work_area'),
        ),
    ]
