# Generated by Django 3.1.1 on 2020-10-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20201012_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentfaults',
            name='databefore',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='instrumentfaults',
            name='repairdata',
            field=models.DateField(default=None),
        ),
    ]
